### ISSUE TITLE
更换无线驱动

### ISSUE THREAD

**Issue by jance-hui** [sinanyolci/Dell-Inspiron-15-5558-OpenCore#1]
大佬。我的电脑的wifi更换了个DW1707，不是DW1820A，使用这个EFI后导致wifi和蓝牙无法使用，有没有什么办法把DW1820A的驱动卸了，换DW1707的驱动呢。

**Comment by sinanyolci** [comment]
Yep, use BTFirmwareUploader kext from insanelymac, then yu bluetooth can work properly
