### ISSUE TITLE
Big Sur boot problem

### ISSUE THREAD

**Issue by marcelloinfoweb** [sinanyolci/Dell-Inspiron-15-5558-OpenCore#3]
I create a bootable pendrive or change the boot that already exists, but it gives the same error.

Attached is a photo of the problem.
![IMG_20210621_221357](https://user-images.githubusercontent.com/2093128/122847777-b3708300-d2de-11eb-93a1-043ca5173f7e.jpg)

**Comment by sinanyolci** [comment]
please select opencore.efi in boot menu.
