### ISSUE TITLE
My laptop is the DELL Inspiron 15 5558. i7-5500u. Can you helpme?

### ISSUE THREAD

**Issue by jhuny-arj** [sinanyolci/Dell-Inspiron-15-5558-OpenCore#5]
My laptop is the Inspiron 15 5558.
i7-5500u (codename:Broadwell-U)
intel wireless dualband (I think Bluetooth is on the same card).
And disable NVIDIA GPU?
I installed the kexts from openintelwireless.github.io itlwm+AirportItlwm+IntelBluetoothFirmware
About wifi, it appears like this on windowsDell Wireless 1707 802.11b/g/n (2.4GHZ) (QualcomAtheros). In the forums it says that the wifi of the inspiron5558 is intel... but I couldn't make it work even with heliport.

I tried different sequences, including recommended sequences from tutorials, but without success in getting the wifi, bluetooth and hdmi to work. :(
(Other Systems/Distros Work All)
Can you help me with this? A Guide, or the EFI ready, whichever is best for you.
Or nothing! :(

I think I'm failing in the Kexts sequences.
My first time trying this.
I'm using an OnlineTranslator... i hope i expressed myself well about it, thanks already.

**Comment by mastermindCodes** [comment]
> I installed the kexts from openintelwireless.github.io itlwm+AirportItlwm+IntelBluetoothFirmware 

**NEVER** use both `itlwm.kext` and `AirportItlwm.kext` at the same time. [ref](https://openintelwireless.github.io/itlwm/Installation.html#installation) 

If you gonna use AirportItlwm make sure to match with your macOS version and remove heliport since it's used for itlwm.

OpenIntelWireless is for Intel but you are saying you have Qualcom Atheros WiFi card ?
Dell Wireless 1707 aka DW1707 is QCNFA335

**Comment by jhuny-arj** [comment]
> > I installed the kexts from openintelwireless.github.io itlwm+AirportItlwm+IntelBluetoothFirmware
> 
> **NEVER** use both `itlwm.kext` and `AirportItlwm.kext` at the same time. [ref](https://openintelwireless.github.io/itlwm/Installation.html#installation)
> 
> If you gonna use AirportItlwm make sure to match with your macOS version and remove heliport since it's used for itlwm.
> 
> OpenIntelWireless is for Intel but you are saying you have Qualcom Atheros WiFi card ? Dell Wireless 1707 aka DW1707 is QCNFA335

Yes.  qualcomm.  I followed different tutorials and I can't make Bluetooth and wifi work... it wasn't at the same time that I used kex itlwm and airport... I didn't find kext QCNFA335 for Monterey.  I googled "qcnfa335 kext Monterey".  Thank you for your quick answer.  do you have any tips on this?
*
Updating: I think I found kext!  I still have to test to confirm... but I think it's this one: "IO80211Family.kext.zip"

**Comment by sinanyolci** [comment]
> > > I installed the kexts from openintelwireless.github.io itlwm+AirportItlwm+IntelBluetoothFirmware
> > 
> > 
> > **NEVER** use both `itlwm.kext` and `AirportItlwm.kext` at the same time. [ref](https://openintelwireless.github.io/itlwm/Installation.html#installation)
> > If you gonna use AirportItlwm make sure to match with your macOS version and remove heliport since it's used for itlwm.
> > OpenIntelWireless is for Intel but you are saying you have Qualcom Atheros WiFi card ? Dell Wireless 1707 aka DW1707 is QCNFA335
> 
> Yes. qualcomm. I followed different tutorials and I can't make Bluetooth and wifi work... it wasn't at the same time that I used kex itlwm and airport... I didn't find kext QCNFA335 for Monterey. I googled "qcnfa335 kext Monterey". Thank you for your quick answer. do you have any tips on this? * Updating: I think I found kext! I still have to test to confirm... but I think it's this one: "IO80211Family.kext.zip"

for other problems you can use the efi here but bluetooth is not working on your wifi card.you can try to replace the wifi card.

**Comment by jhuny-arj** [comment]
ok, thanks.
